version: '3.7'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--ping=true"
      - "--log.level=ERROR"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.default.address=:80"
    networks:
      - 'ovpn'
    ports:
      - "${TRAEFIK_BIND_ADDRESS:-0.0.0.0}:${TRAEFIK_BIND_PORT:-80}:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefikapi.rule=PathPrefix(`/api/`) && HeadersRegexp(`Referer`, `^https?:\/\/.+\/traefik\/dashboard\/`)'
      - 'traefik.http.routers.traefikapi.entrypoints=default'
      - 'traefik.http.routers.traefikapi.service=api@internal'
      - 'traefik.http.routers.traefikapi.middlewares=traefik-auth'
      - 'traefik.http.routers.traefikdashboard.rule=PathPrefix(`/traefik/dashboard/`)'
      - 'traefik.http.routers.traefikdashboard.entrypoints=default'
      - 'traefik.http.routers.traefikdashboard.service=api@internal'
      - 'traefik.http.routers.traefikdashboard.middlewares=traefik-auth,traefik-stripprefix'
      - 'traefik.http.middlewares.traefik-stripprefix.stripprefix.prefixes=/traefik'
      - 'traefik.http.middlewares.traefik-auth.basicauth.users=admin:{SHA}0tTNr469Z7oY3fDRwNoUXE2vTBw='
    depends_on:
      ovpn-admin:
        condition: service_healthy
    healthcheck:
      test: traefik healthcheck --ping
      start_period: 5s
      interval: 5s
      retries: 30
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
  ovpn:
    build:
      context: src/openvpn
    environment:
      OVPN_SERVER_NET: "172.16.0.0"
      OVPN_SERVER_MASK: "255.255.248.0"
    cap_add:
      - NET_ADMIN
    networks:
      - ovpn
    ports:
      - "${OVPN_BIND_ADDRESS:-0.0.0.0}:${OVPN_BIND_PORT_TCP:-1194}:1194/tcp"
      - "${OVPN_BIND_ADDRESS:-0.0.0.0}:${OVPN_BIND_PORT_UDP:-1194}:1194/udp"
    # healthcheck:
    #   test: "/etc/openvpn/setup/check_openvpn -p 1194 --tls-auth /etc/openvpn/easyrsa/pki/ta.key 127.0.0.1"
    #   start_period: 5s
    #   interval: 30s
    #   retries: 3
    deploy:
      restart_policy:
        condition: always
        delay: 5s
      resources:
        limits:
          memory: ${OVPN_MEMORY_LIMIT_MB:-512}M
    volumes:
      - ovpn-easyrsa:/etc/openvpn/easyrsa
      - ovpn-ccd:/etc/openvpn/ccd

  ovpn-admin:
    build:
      context: src/openvpn-admin
    environment:
      OVPN_DEBUG: "False"
      OVPN_VERBOSE: "False"
      OVPN_NETWORK: "172.16.0.0/21"
      EASYRSA_PATH: "/mnt/easyrsa"
      OVPN_SERVER: "${OVPN_PUBLIC_HOST:-127.0.0.1}:${OVPN_BIND_PORT_TCP:-1194}:udp"
      OVPN_INDEX_PATH: "/mnt/easyrsa/pki/index.txt"
    networks:
      - ovpn
    depends_on:
      ovpn:
        condition: service_healthy
    deploy:
      restart_policy: 
        condition: always
        delay: 5s
      resources:
        limits:
          memory: ${OVPN_ADMIN_MEMORY_LIMIT_MB:-128}M
    volumes:
      - ovpn-easyrsa:/mnt/easyrsa
      - ovpn-ccd:/mnt/ccd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ovpn-admin.entrypoints=default"
      - "traefik.http.routers.ovpn-admin.rule=PathPrefix(`/`)"
      - 'traefik.http.routers.ovpn-admin.middlewares=ovpn-admin-auth'
      - "traefik.http.services.ovpn-admin.loadbalancer.server.port=8080"
      - 'traefik.http.middlewares.ovpn-admin-auth.basicauth.users=admin:{SHA}0tTNr469Z7oY3fDRwNoUXE2vTBw='

volumes:
  ovpn-easyrsa:
    driver: local
  ovpn-ccd:
    driver: local

networks:
  ovpn: